import { Octokit } from "octokit";
import type { FileChange, GeminiAnalysis } from "./schemas";

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

const owner = () => process.env.GITHUB_OWNER!;
const repo = () => process.env.GITHUB_REPO!;
const branch = () => process.env.GITHUB_BRANCH || "main";

export async function getRepoTree(): Promise<string[]> {
  const { data: refData } = await octokit.rest.git.getRef({
    owner: owner(),
    repo: repo(),
    ref: `heads/${branch()}`,
  });
  const commitSha = refData.object.sha;

  const { data: commitData } = await octokit.rest.git.getCommit({
    owner: owner(),
    repo: repo(),
    commit_sha: commitSha,
  });

  const { data: treeData } = await octokit.rest.git.getTree({
    owner: owner(),
    repo: repo(),
    tree_sha: commitData.tree.sha,
    recursive: "1",
  });

  return treeData.tree
    .filter((item) => item.type === "blob")
    .map((item) => item.path!);
}

export async function getFileContent(path: string): Promise<string> {
  const { data } = await octokit.rest.repos.getContent({
    owner: owner(),
    repo: repo(),
    path,
    ref: branch(),
  });
  if ("content" in data && data.content) {
    return Buffer.from(data.content, "base64").toString("utf-8");
  }
  throw new Error(`Could not read file: ${path}`);
}

export async function listDirectory(directory: string): Promise<string[]> {
  const tree = await getRepoTree();
  const prefix =
    directory === "/" || directory === ""
      ? ""
      : directory.replace(/^\//, "").replace(/\/$/, "") + "/";
  if (!prefix) return tree;
  return tree.filter((p) => p.startsWith(prefix));
}

export async function commitFiles(
  files: FileChange[],
  commitMessage: string
): Promise<string> {
  const { data: refData } = await octokit.rest.git.getRef({
    owner: owner(),
    repo: repo(),
    ref: `heads/${branch()}`,
  });
  const currentCommitSha = refData.object.sha;

  const { data: commitData } = await octokit.rest.git.getCommit({
    owner: owner(),
    repo: repo(),
    commit_sha: currentCommitSha,
  });
  const currentTreeSha = commitData.tree.sha;

  const treeItems = await Promise.all(
    files.map(async (file) => {
      const { data: blob } = await octokit.rest.git.createBlob({
        owner: owner(),
        repo: repo(),
        content: Buffer.from(file.content).toString("base64"),
        encoding: "base64",
      });
      return {
        path: file.path.replace(/^\//, ""),
        mode: "100644" as const,
        type: "blob" as const,
        sha: blob.sha,
      };
    })
  );

  const { data: newTree } = await octokit.rest.git.createTree({
    owner: owner(),
    repo: repo(),
    base_tree: currentTreeSha,
    tree: treeItems,
  });

  const { data: newCommit } = await octokit.rest.git.createCommit({
    owner: owner(),
    repo: repo(),
    message: commitMessage,
    tree: newTree.sha,
    parents: [currentCommitSha],
  });

  await octokit.rest.git.updateRef({
    owner: owner(),
    repo: repo(),
    ref: `heads/${branch()}`,
    sha: newCommit.sha,
  });

  return newCommit.sha;
}

// ── GitHub Issues ─────────────────────────────────────────────────────────────

export async function createGitHubIssue(params: {
  diagnosisId: string;
  analysis: GeminiAnalysis;
  pageUrl: string;
  voiceTranscript: string;
  screenshotUrl?: string | null;
}): Promise<number> {
  let body = `## Bug Report (auto-generated by GhostBuster)\n\n`;
  body += `**Diagnosis ID:** \`${params.diagnosisId}\`\n`;
  body += `**Page URL:** ${params.pageUrl}\n\n`;
  body += `### Description\n${params.analysis.bug_description}\n\n`;
  body += `### Affected Component\n${params.analysis.affected_component}\n\n`;
  body += `### Root Cause\n${params.analysis.root_cause}\n\n`;
  body += `### Suggested Fix\n${params.analysis.suggested_fix}\n\n`;
  body += `### User Voice Description\n> ${params.voiceTranscript}\n\n`;

  if (params.screenshotUrl) {
    body += `### Screenshot\n![Bug Screenshot](${params.screenshotUrl})\n\n`;
  }

  body += `---\n*This issue was created automatically by GhostBuster. An agent is working on a fix.*`;

  const { data } = await octokit.rest.issues.create({
    owner: owner(),
    repo: repo(),
    title: `[GhostBuster] ${params.analysis.bug_description.slice(0, 80)}`,
    body,
    labels: ["bug", "ghostbuster"],
  });

  return data.number;
}

export async function closeGitHubIssue(
  issueNumber: number,
  commitSha: string,
  filesChanged: string[]
): Promise<void> {
  // Add closing comment with fix details
  const comment =
    `## Fix Deployed\n\n` +
    `**Commit:** [\`${commitSha.slice(0, 7)}\`](https://github.com/${owner()}/${repo()}/commit/${commitSha})\n` +
    `**Files changed:** ${filesChanged.map((f) => `\`${f}\``).join(", ")}\n\n` +
    `This issue was automatically fixed and deployed by the GhostBuster agent.`;

  await octokit.rest.issues.createComment({
    owner: owner(),
    repo: repo(),
    issue_number: issueNumber,
    body: comment,
  });

  await octokit.rest.issues.update({
    owner: owner(),
    repo: repo(),
    issue_number: issueNumber,
    state: "closed",
    state_reason: "completed",
  });
}
